### ISSUE TITLE
Users cannot label expected means matrix

### ISSUE THREAD

**Issue by mcneale** [OpenMx/OpenMx#333] opened 2021-11-30 11:26 UTC
If the user correctly labels the means matrix, it generates an error.  Ideally, the names and their order should be compared; if different then error, otherwise proceed.

> twinModel1out <- mxRun(twinModel1)
Error: The expected means matrix associated with the expectation function in model 'DZ' contains dimnames:  mean, c("BMI1", "SBP1", "FTO1", "BMI2", "SBP2", "FTO2"). The expectation function has specified dimnames: BMI1, SBP1, FTO1, BMI2, SBP2, FTO2.

**Comment by jpritikin** [comment] 2021-11-30 16:20
I think the problem is that you labelled the row. I suggest we only compare the colnames?

**Comment by tbates** [comment] 2021-11-30 16:32
I guess it's been conventional for the row element of the dim names list to be NULL, so they don't get checked.

```R
mxMatrix("Full",1, 3, free = TRUE, dimnames = list(NULL, selVars))
```
Not sure if there would be side effects of ignoring non-Null row names. Might be best to say:
> The row names of the expected means matrix associated with the expectation function in model 'DZ' contains dimnames: mean. The expectation function expected  row dimnames to be NULL

**Comment by mcneale** [comment] 2021-11-30 17:03
> 

Actually, I labelled both.  With either "mean" for a row name (as above) or NULL, it is not happy at all about column labels on the mean algebra.

**Comment by jpritikin** [comment] 2021-11-30 17:54
See if v2.19.8-69-g638043f07 solves it

**Comment by tbates** [comment] 2022-02-17 21:58
Here's an example. It appears to work: The means fix fixed the algebra double naming also...
But exposes an issue where other functions (at least `mxStandardizeRAMpaths` don't work (see below).

```R
data(HS.ability.data)  # load the data
Spatial = c("visual", "cubes", "paper")
m1 = umxRAM(model= "Holzinger_and_Swineford_1939", data = HS.ability.data,
    umxPath(from = "vis",  to = Spatial),
    umxPath(v1m0 = "vis"),
    umxPath(v.m. = Spatial),
	mxAlgebra(name = "myMcols", M, dimnames = list(NULL, c(Spatial, "vis"))),
	mxAlgebra(name = "myMboth", M, dimnames = list("means", c(Spatial, "vis")))
)
m1$expectation$M = "myMcols"
m1 = mxRun(m1)

m1$expectation$M = "myMboth"
m1 = mxRun(m1)
``` 
so far so good but other functions are not happy with the M matrix being an algebra, I think?

```R
mxStandardizeRAMpaths(m1)
```
> Error in out$label[j] <- model_M$labels[1, M_need_pos[i]] : 
  replacement has length zero

**Comment by RMKirkpatrick** [comment] 2024-12-04 18:58
With issue #334 closed, `mxStandardizedRAMpaths()` runs in your example.  The only weird thing is that it reports SEs of zero for the 3 _raw_ means.  I'd call that a bug.

In light of that and of commit 638043f, can we close this issue, and maybe open a new one about the raw-SEs bug in `mxStandardizedRAMpaths()`?

**Closed** 2024-12-04 19:54 UTC
