### ISSUE TITLE
mxDataWLS allContinuousMethod='marginals'

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#120] opened 2018-12-05 10:40 UTC
It is reasonable to expect the same WLS strategy that works for ordinal and joint data would work for continuous data, but yet it doesn't.

Options altering what happens with all-continuous in mxDataWLS

1. Change the default for allContinuousMethod to  'marginals'
2. Print a message
   * "You selected 'cumulants', so you ain't gettin' no darn means for Christmas."
   * "You selected marginals, so missing data will suck."
3. No default for allContinuousMethod
   * force user to say what they want when data are all continuous.
   * (In the case of ordinal and joint data, we would not require any user input for this argument.)

Should add the effect of allContinuousMethod choices to `mxDataWLS` Rd anyway

**Comment by tbates** [comment] 2018-12-05 10:42
What if any, are the up/downsides of `cumulants` vs. `marginals`. Not having means seems like a no-cost for many models, especially compared to dropping all rows with any missing data.

**Comment by tbates** [comment] 2018-12-05 10:53
My naive preference is to remove the default. Users should actively choose, given the significant down stream impact on modeling (means vs no means in model).

Also for more explanatory guidance to the `mxDataWLS` Rd on the pluses and minefields of all this.

**Comment by jpritikin** [comment] 2018-12-05 18:22
> What if any, are the up/downsides of cumulants vs. marginals.

Cumulants should be much more accurate because the whole covariance is a single analytic expression. No estimation is involved.

**Comment by jpritikin** [comment] 2018-12-05 18:24
> You selected marginals, so missing data will suck.

I'm presently adding missing data support to marginals.

**Comment by tbates** [comment] 2018-12-05 18:46
Thanks Josh!
`cumulants` are quicker (from Rd) AND more accurate... so unless one really wants means, this is a no-brainer. I will start making changes to umx functions to cope with this means/no-means switch based on cumulants vs. marginals.

And good news, on missingness for marginals - this seemed hard, so might be worth a bioarxiv note.

**Comment by mcneale** [comment] 2018-12-05 19:12
By support for missing data, is that pairwise deletion?  If so, a disadvantage would be the possibility of generating a non-positive definite covariance matrix.  Might be worth a warning if we spot that it is?

**Comment by RMKirkpatrick** [comment] 2018-12-05 19:21
@mcneale A warning in that situation isn't a bad idea.

**Comment by jpritikin** [comment] 2018-12-05 19:23
> And good news, on missingness for marginals - this seemed hard, so might be worth a bioarxiv note.

The method I'm familiar with isn't hard, but it isn't particularly accurate either. The problem is the denominator. Do you divide by the total sample size or the number of non-missing values? I don't think there is a best answer.

**Comment by mcneale** [comment] 2018-12-05 19:42
The pairwise correlation matrix could be non-positive as well (it's a bit like building a correlation matrix from different samples).   
Since definition of positive definite is 
x' M x > 0  for all non-null x, if M = DCD where D is diagonal standard deviations and C is correlation matrix, then 
x' M x =   x' (DCD) x
           =   x'Dx %*% x'Cx %*% x'Dx
but if  x'Cx <= 0 then covariance matrix  DCD won't be positive definite whenever C isn't.  Regardless of whether D is pd (which it should  be).

**Comment by jpritikin** [comment] 2018-12-05 21:33
> covariance matrix DCD won't be positive definite either

Hm, OK. Here you go v2.11.5-85-gc28f8582d

I leave it to you to write a test.

**Comment by mcneale** [comment] 2018-12-06 20:19
Cool, will do.  BTW new warnings from omxDefines.h on compiling this version, compared to v2.11.5 original.

   In file included from omxState.h:31:0,
                    from glue.h:23,
                    from Compute.cpp:24:
   omxDefines.h: In constructor ‘AssertProtectStackBalanced::AssertProtectStackBalanced(const char*, ProtectAutoBalanceDoodad&)’:
   omxDefines.h:477:14: warning: ‘AssertProtectStackBalanced::context’ will be initialized after [-Wreorder]
     const char *context;
                 ^~~~~~~
   omxDefines.h:476:28: warning:   ‘ProtectAutoBalanceDoodad& AssertProtectStackBalanced::myDoodad’ [-Wreorder]
     ProtectAutoBalanceDoodad &myDoodad;
                               ^~~~~~~~
   omxDefines.h:481:3: warning:   when initialized here [-Wreorder]
      AssertProtectStackBalanced(const char *_context,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by mhunter1** [comment] 2018-12-07 01:33
Marked code block

**Comment by tbates** [comment] 2018-12-18 19:41
Note too that these changes to how we do WLS are highly backward incompatible - I've spent the week re-writing umx to cope, because the type parameter now doesn't  reflect the datatype (raw can be raw, or going to be WLS). This both breaks existing code, and makes processing WLS data hard, as the user has to deduce that the type is not in fact going to be raw, and predict whether the resultant type will or will not have means...

I'd much prefer the old function just carrying on as it did or at least gaining the ability to actually process the data into WLS so that the has means flag can be set in a way that doesn't require deductions (which might break if the code changes/improves).

**Comment by jpritikin** [comment] 2018-12-18 19:53
@tbates You could pass compute=TRUE to mxDataWLS, but in this case it is not possible to use exogenous covariates.

**Comment by jpritikin** [comment] 2018-12-18 20:22
> I'd much prefer the old function just carrying on as it did

The old function was conceptually inconsistent because `type` specified the type of the data (`raw` or `cov` or whatever) and also whether the data was prepared for WLS (`type=acov`). Now these are indicated separately.

**Comment by jpritikin** [comment] 2019-01-04 16:11
I believe all this stuff is done.

**Closed** 2019-01-04 16:10 UTC
Labels: better errors, enhancement
