### ISSUE TITLE
TwinAnalysis_Multivariate_Matrix_Raw.R Error

### ISSUE THREAD

**Issue by smasongarrison** [OpenMx/OpenMx#9] opened 2016-04-05 15:07 UTC
In the TwinAnalysis_Multivariate_Matrix_Raw.R file,
the current version of the code throws an error. 
> fit = mxRun(model)
Running ACE with 11 parameters
Warning message:
In model 'ACE' Optimizer returned a non-zero status code 6. The model does not satisfy the first-order optimality conditions to the required accuracy, and no improved point for the merit function could be found during the final linesearch (Mx status RED) 

In addition,  the estimate no longer returns the correct result

```r
print(ACEest);
#          A1    A2 C1 C2     E1    E2
# ht1   0.938 0.000  0  0  0.345 0.000
# bmi1 -0.030 0.883  0  0 -0.145 0.445
```
is now

```r
print(ACEest);
#          A1    A2 C1 C2     E1    E2
# ht1   **-0.938** 0.000  0  0  0.345 0.000
# bmi1 -0.030 0.883  0  0 -0.145 0.445
```

**Comment by RMKirkpatrick** [comment] 2016-04-05 15:48
I am not able to reproduce the reported behavior on my system.  When using NPSOL as the optimizer, I get the return value of `print(ACEest)` anticipated in the script comment, and when using SLSQP as the optimizer, I get an equivalent solution (with the signs of a11 and a12 swapped).  I do get a status code 6, though, but that's only a warning and not a fatal error.

My `mxVersion()` output:

> > mxVersion()
> OpenMx version: 2.3.1.333 [GIT v2.3.1-333-g98c0dd1-dirty]
> R version: R version 3.1.1 (2014-07-10)
> Platform: i386-w64-mingw32
> Default optimiser: NPSOL

@smasongarrison , what is your output from `mxVersion()`?

**Comment by mhunter1** [comment] 2016-04-06 16:32
I must be missing something.  The "error" reported is not an error.  It's a warning.  These are not the same.  http://rfunction.com/archives/1377

Also, the old and new ACEest look identical to me.  @smasongarrison recall that the parameter estimates for this model are not unique. Sign flips can occur each of the Cholesky factors without changing the fit.  If you need a unique solution, then place a lower bound of 0 on the diagonal elements of the Cholesky matrices: OpenMx names a, c, e; R names aMatrix, cMatrix, eMatrix.

**Comment by RMKirkpatrick** [comment] 2016-04-06 16:38
@smasongarrison , can you confirm that the sign of both values you're getting in the "A1" column are negative?  Because if only one of them is negative, then those values are just an equivalent solution (like I described in my previous post) to what is expected in the code comment.  But if both are negative, then those parameter values imply a genetic covariance that is equal in magnitude to what is expected, but of opposite sign (positive instead of negative)--which WOULD be pretty weird.

**Comment by tbates** [comment] 2016-09-28 12:53
I can't replicate this. Note too that there is a lower bound of 0 on the diagonal of each of a, c, and e, so it should not be flipping sign.

    aMatrix$lbound
    [,1] [,2]
    [1,]    0   NA
    [2,]   NA    0

So, closing as not-reproducible - @smasongarrison if you see this and can still reproduce, then please reply to @RMKirkpatrick regarding his question of whether only one, or both of the values for A1 were flipping sign.

**Closed by tbates** 2016-09-28 12:53 UTC

**Comment by RMKirkpatrick** [comment] 2016-09-28 14:34
@tbates I believe Mike Hunter added the lower bound to the diagonal elements after this issue was reported, to ensure that the sign would never flip in the future.
