### ISSUE TITLE
Error offering up a label name to mxSE

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#154] opened 2019-03-24 00:23 UTC
When I offer up a label as an unquoted expression, mxSE works, but offered a quoted string (`"X"`  - the label of a parameter in the model) it throws an error:

```R
mData = matrix (1)
dimnames(mData) = list(c("X"), c("X"))

m1 = mxModel("one_is_the_loneliest_number", type="RAM",
	manifestVars = "X",
	mxPath(from="X", to = "X", arrows=2, lbound=0, labels= "X"),
	mxData(mData, type="cov", numObs = 10)
)
m1 = mxRun(m1)

# this works fine
mxSE(X, m1) #  0.4024916

# this errors

mxSE("X", m1)
Treating first argument as character named entity in the model
Error in convertForBackend(flatModel@compute, flatModel, model) : 
  Can only apply MxComputeJacobian to MxAlgebra *or* MxExpectation not "X"

```

Also "character named entity in the model" is not particularly clear. Should it say just "named entity in the model"?

Also, the Rd says "It is a frontend-only file" (file = typo for function?) so why is it calling `convertForBackend`?

**Comment by mcneale** [comment] 2019-03-24 16:08
I figure this is an issue with giving a path the same name as a variable.  Same issue if you call the path VarX?

**Comment by tbates** [comment] 2019-03-24 16:11
change path name to be unique.... no improvement

```R
mData = matrix (1)
dimnames(mData) = list(c("X"), c("X"))

m1 = mxModel("one_is_the_loneliest_number", type="RAM",
	manifestVars = "X",
	mxPath(from="X", to = "X", arrows=2, lbound=0, labels= "Xmike"),
	mxData(mData, type="cov", numObs = 10)
)
m1 = mxRun(m1)

mxSE("Xmike", m1)
```
> Treating first argument as character named entity in the model
> Error in convertForBackend(flatModel@compute, flatModel, model) : 
>   Can only apply MxComputeJacobian to MxAlgebra *or* MxExpectation not "Xmike"

**Comment by mcneale** [comment] 2019-03-24 17:14
Yep, this seems weird to me too - something to do with the RAM context perhaps.   Bump to Rob?

**Comment by RMKirkpatrick** [comment] 2019-03-24 20:15
> Also "character named entity in the model" is not particularly clear. Should it say just "named entity in the model"?

Let's make it "character-named entity in the model".

> Also, the Rd says "It is a frontend-only file" (file = typo for function?) so why is it calling convertForBackend?

Good point.  It's no longer the case that `mxSE()` is a frontend-only function, because it now uses the backend to calculate the Jacobian .

**Comment by tbates** [comment] 2019-03-24 20:18
So a bug has been introduced in the move to calculate the Jacobian in the backend, such that the label is being sent to the backend, instead of an MxAlgebra or MxExpectation

**Comment by RMKirkpatrick** [comment] 2019-03-24 20:20
> Can only apply MxComputeJacobian to MxAlgebra or MxExpectation not "Xmike"

I reproduce this error.  It results from the MxComputeJacobian step being presently unable to differentiate anything besides an MxAlgebra or an MxExpectation.  @jpritikin , any thoughts?

**Comment by tbates** [comment] 2019-03-24 20:53
In addition, mxSE is issuing a warning that the model has been changed, when it hasn't
```R
mData = matrix (1)
dimnames(mData) = list(c("X"), c("X"))

m1 = mxModel("one_is_the_loneliest_number", type="RAM",
	manifestVars = "X",
	mxPath(from="X", to = "X", arrows=2, lbound=0, labels= "X"),
	mxData(mData, type="cov", numObs = 10)
)
m1 = mxRun(m1)
mxSE(X, m1) #  0.4024916
```
> Warning message:
> In assertModelRunAndFresh(object) :
>  MxModel 'one_is_the_loneliest_number' was modified since it was run.

**Comment by tbates** [comment] 2019-03-24 21:02
Added a script to check mxSE with RAM model into failing... 

`~/bin/OpenMx/inst/models/failing/check_mxSE_works.R`

**Comment by RMKirkpatrick** [comment] 2019-03-24 22:00
> In addition, mxSE is issuing a warning that the model has been changed, when it hasn't

It has been changed, though.  `mxSE()` has internally changed it.  I bet the warning is being raised during the call to when `mxSE()` internally calls the `vcov` method for MxModels, because `assertModelRunAndFresh(object)` is the first thing that method does.

**Comment by tbates** [comment] 2019-03-24 23:34
Either `mxSE` should suppress warnings or (more likely) we should just turn off `vcov` warning and trust that users asking for things from models they've modified want things from models they've modified.

I've got a feeling that, as we head to being a mature version 3.0 app, we give the user too many warnings. 

Probably should add a test suit item to check that warnings are not being raised in the course of normal user work.

**Comment by mcneale** [comment] 2019-03-25 12:34
The distinctions between Note: Warning: and Error: should be clarified and made as consistent as possible.

@tbates - have you come across Warnings that should be downgraded to Note (which seems kindest to the user)?  If so, please keep a list.

**Comment by jpritikin** [comment] 2019-03-25 14:19
> Probably should add a test suit item to check that warnings are not being raised in the course of normal user work.

We already display all warnings triggered if no tests fail. It's just a matter of somebody volunteering to audit them.

**Comment by jpritikin** [comment] 2019-03-25 14:20
> have you come across Warnings that should be downgraded to Note (which seems kindest to the user)? If so, please keep a list.

Don't make a list. Just change 'em.

**Comment by jpritikin** [comment] 2019-03-25 14:23
> When I offer up a label as an unquoted expression, mxSE works, but offered a quoted string ("X" - the label of a parameter in the model) it throws an error:

Why is this a bug? To handle this kind of distinction, we have `mxAlgebra` and `mxAlgebraFromString`. Do you want `mxSEFromString`?

**Comment by tbates** [comment] 2019-03-25 14:31
@jpritikin:   X is a valid algebra in this model - so should be handled by `mxAlgebraFromString` - indeed it is being handled, but with an error. 

No need for `mxSEFromString`, as that is what mxSE("X", m1) should be doing: computing the SE of  `mxAlgebraFromString("X")`

**Comment by RMKirkpatrick** [comment] 2019-03-25 14:33
@jpritikin I think this is a bug because it's a regression.  What @tbates is trying to do used to work.

Proposed solution: use the backend to calculate the Jacobian if possible (i.e., if `x` is an MxAlgebra or MxExpectation), and use the old frontend code (using the 'numDeriv' package, right?) to calculate it otherwise.

**Comment by tbates** [comment] 2019-03-25 14:44
@mcneale I'll look at the warnings and notes and change where possible to down grade if reasonable, and ensure user knows the origin and meaning of the message.

Here's an example of a good, non-distracting note, IMHO:

```R
message("Polite note from mxTryHard: Hessian not checked as model contains mxConstraints")
```

**Comment by tbates** [comment] 2019-03-25 16:52
Thanks! Great turn-around!

**Comment by tbates** [comment] 2019-05-14 19:09
This model appears to expose a problem with mxSE()

*need to rename the file test.Rd and it should double-click open and load() a model called `model` into your workspace*

[test.txt](https://github.com/OpenMx/OpenMx/files/3179381/test.txt)


```R
load(test.Rd)
names(model$algebras)
# [1] "i_1" "i_2"

# This works:
mxSE(i_1, model)
#           [,1]
# [1,] 0.01815302

# Even this works
mxSE("i_1", model) 
# [1,] 0.01815302

# But this fails (i.e., can't put string name of algebra into a variable...

thisAlg = "i_1"
mxSE(thisAlg, model, forceName=TRUE)

```
> Error: The reference 'thisAlg' is unknown in the algebra named 'crime_model.onTheFlyAlgebra'
In addition: Warning message:
In is.na(x) : is.na() applied to non-(list or vector) of type 'symbol'

**Comment by RMKirkpatrick** [comment] 2019-05-14 19:12
RTFM:
> 

forceName | logical; defaults to FALSE. Set to TRUE if x is an R symbol that refers to a character string.
-- | --

**Comment by tbates** [comment] 2019-05-14 19:17
correct

**Comment by RMKirkpatrick** [comment] 2019-05-14 19:20
Well, I can't reproduce what you report on my system, because I get

> Error in imxConvertIdentifier(.Object@algebra, modelname, namespace, TRUE) : 
  no slot of name "algebra" for this object of class "MxDataStatic"

for all three calls to `mxSE()`.  But let's reopen this issue.

**Comment by tbates** [comment] 2019-05-17 14:47
So the slot of name "algebra" for this object of class "MxDataStatic" turns out to reflect a new alpha `algebra` parameter for mxData... Fixed now. see #185

**Comment by RMKirkpatrick** [comment] 2019-05-17 18:47
I know @mhunter1 assigned this to himself, but I just looked into this issue and the fix looked really easy.  See 9937069.  Can we close this?

**Closed** 2019-05-17 21:58 UTC
Labels: bug

**Comment by mhunter1** [comment] 2019-05-18 01:34
@RMKirkpatrick It looks like I clobbered your changes with mine.  Feel free to review/modify.
