### ISSUE TITLE
logLik obs : attempt to set an attribute on NULL

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#279] opened 2020-07-10 14:58 UTC
A user reported that `logLik.MxModel` is broken for a DWLS model they ran

I verified this using the model they shared with me:
`logLik(m1)`
> Error in attr(ll, "nobs") <- nobs : attempt to set an attribute on NULL

FYI
```R
model@output$fitUnits
"r'Wr"
model@output$chi
NULL
model@output$Minus2LogLikelihood
3226.109
OpenMx:::numberObservations(model@runstate$datalist, model@runstate$fitfunctions)
[1] 5724
```
Looks like it needs to check output is not NULL?

There's some comments in `logLik.MxModel` suggesting it might be useful to check it is doing things right.

**Comment by mcneale** [comment] 2020-07-10 15:14
This seems reasonable to me.  There is no -2lnL when using WLS.  It's not a maximum likelihood fit function, so there's no likelihood to logarithm and multiply by -2.

BUT, the error message is bloody awful and should be fixed.

**Comment by tbates** [comment] 2020-07-10 15:24
It needs to return without error as it gets called by other functions, and should just return NA or NULL when that's the correct answer, and callers can handle that.

It's odd that the Minus2LogLikelihood slot has a value when it's not an ML function.

**Comment by mcneale** [comment] 2020-07-10 15:56
It might be bc _sometimes_ WLS fit differences can be similarly regarded as asymptotically distributed as chi-squared distributed.

**Comment by RMKirkpatrick** [comment] 2020-07-10 16:03
@tbates , what version of OpenMx is the user running?  I suspect it's out-of-date.

**Comment by tbates** [comment] 2020-07-10 16:11
Hi @RMKirkpatrick. The model was created under 2.17.3, so pretty up to date, but I re-ran under 2.17.4 [GIT v2.17.4] and the bug replicates.

**Comment by RMKirkpatrick** [comment] 2020-07-10 16:32
@tbates : OK, just checking.

**Comment by mhunter1** [comment] 2020-07-10 18:36
`logLik` is meant to return the chi-squared value for WLS models.  In your case, @tbates , the `model@output$chi` is `NULL`.  It's failing ungracefully and that should be fixed.

A sufficient solution is for OpenMx to check if `model@output$chi` is null, and in that case return NA or NULL.

However, I'd like to know why `model@output$chi` is `NULL` for this model.  I'm concerned about the presence of some bug or failure of the OpenMx WLS implementation that makes `model@output$chi` null when it should not be null.  We don't currently check for `model@output$chi` being null because I anticipated it never being null.  It should automatically have a value for all WLS models.

Can you provide details on the model?  Is it multigroup?  Is there a minimal working example?  Is it similar to a model that we already have in the test suite but haven't checked this aspect of?

**Comment by tbates** [comment] 2020-07-10 22:37
I'll email the model to you direct @mhunter1 (it's 3MB and contains private data) It's a umxIP twin model, so yes, multi group.

**Comment by tbates** [comment] 2020-07-31 16:10
Any update? current student using WLS for twin modelling is stumped by this

**Comment by tbates** [comment] 2020-07-31 16:34
Will check: What version is that fix in? Is it on CRAN for Mac, or travis?

**Comment by RMKirkpatrick** [comment] 2020-07-31 16:38
@tbates It was repaired with 03b29e4 on May 11th.  It has not been included in any release, though travis has probably built a macOS binary that includes it.

There's a simple workaround: run your model through `mxRun()` after you get it back from `mxTryHard()`.

**Comment by tbates** [comment] 2020-08-19 07:36
So this is still a bug for `logLik` with WLS, doesn't go away with mxRun after tryHard

travis build OpenMx version: 2.17.3.161 [GIT v2.17.3-161-g5a04c0e9]

**Comment by mhunter1** [comment] 2020-09-04 12:42
@tbates I haven't been able to replicate the problem.  For example with the below code from `?umxIP`, everything works fine.

```
require(umx)
data(GFF)
mzData <- subset(GFF, zyg_2grp == "MZ")
dzData <- subset(GFF, zyg_2grp == "DZ")
selDVs = c("gff","fc","qol","hap","sat","AD") # These will be expanded into "gff_T1" "gff_T2" etc.
m1 =    umxIP(selDVs = selDVs, sep = "_T", dzData = dzData, mzData = mzData)

# WLS example: Use "marginals" method to enable all continuous data with missingness.
m3 = umxIP(selDVs = selDVs, sep = "_T", dzData = dzData, mzData = mzData, 
	type = "DWLS", allContinuousMethod='marginals')
logLik(m3)
# 'log Lik.' 1869.854 (df=138)
```

To me, this suggests that the problem is not widespread, but rather is an odd corner case you've encountered.  So, `logLik` works fine with many, many models (including multigroup WLS models), but you've found that there exists at least one model where it fails.

@tbates I know you sent me a Dropbox link to a file that replicates the problem, but I waited too long and it it expired.  Can you re-send the link?

**Comment by tbates** [comment] 2020-09-04 14:51
it was probably from some of the other WLS bugs. Will try and find the broken model link but it might not open now (new versions and all).

Would be good still if that slot is empty to just return NA from logLik() ?

**Comment by RMKirkpatrick** [comment] 2020-09-04 15:02
@mhunter1 How up-to-date is your clone of the repository?  I recently made a change to `logLik.MxModel` that isn't reflected in your copy-paste there.

**Comment by RMKirkpatrick** [comment] 2020-09-04 15:04
See 5e13986 and 1572c25 .

**Comment by mhunter1** [comment] 2020-09-21 19:43
@tbates This should be resolved now.  @jpritikin committed 8b596bc4e2526b7bfef280e8debc3c1cfcffc97a which should fix it.

The problem had to do with the presence of constraints with WLS.  There was some old code that needed to be removed.

The following code now seems to work:

```
setwd("~/../Downloads/")
require(OpenMx)
require(umx)

# m1 = umxIP(name = "m1_IP_413_111", selDVs = selDVs1, dzData=dzData, mzData=mzData, sep="_T", nFac = c(a=4,c=1,e=3), type = "DWLS")
# m2 = umxModify(m1, update = c("ai_r1c1", "ai_r2c1", "ai_r3c1", "ai_r4c1", "ai_r5c1", "ai_r6c1", "ai_r7c1", "ai_r8c1", "ai_r9c1", "ai_r10c1", "ai_r11c1", "ai_r12c1"), name = "m2_IP_313_111")

load("m1.rda")
load("m2.rda")

m1r <- mxRun(m1)

m2r <- mxRun(m2)


logLik(m1r)

logLik(m2r)
```

It produces the following output:
```
> setwd("~/../Downloads/")
> require(OpenMx)
Loading required package: OpenMx
Notice: R GUI cannot display verbose output from the OpenMx backend. If you need detail diagnostics then R CMD BATCH is one option.
> require(umx)
Loading required package: umx
For an overview type '?umx'

Attaching package: ‘umx’

The following object is masked from ‘package:stats’:

    loadings

Warning message:
package ‘umx’ was built under R version 4.0.2 
> 
> load("m1.rda")
> load("m2.rda")
> 
> m1r <- mxRun(m1)
Running m1_IP_413_111 with 144 parameters

MxComputeGradientDescent(SLSQP) evaluations 6483 fit 833.669 change -2.086e-08
                                                                              
Warning messages:
1: In warnModelCreatedByOldVersion(model) :
  You are using OpenMx version 2.18.1.29 with a model created by OpenMx version 2.17.3.162. This may work fine (fingers crossed), but if you run into trouble then please recreate your model with the current version of OpenMx.
2: In runHelper(model, frontendStart, intervals, silent, suppressWarnings,  :
  constraint-adjusted standard errors could not be calculated because the sampling covariance matrix was uninvertible
3: In model 'm1_IP_413_111' Optimizer returned a non-zero status code 6. The model does not satisfy the first-order optimality conditions to the required accuracy, and no improved point for the merit function could be found during the final linesearch (Mx status RED) 
> 
> m2r <- mxRun(m2)
Running m2_IP_313_111 with 132 parameters
Warning messages:
1: In warnModelCreatedByOldVersion(model) :
  You are using OpenMx version 2.18.1.29 with a model created by OpenMx version 2.17.3.162. This may work fine (fingers crossed), but if you run into trouble then please recreate your model with the current version of OpenMx.
2: In runHelper(model, frontendStart, intervals, silent, suppressWarnings,  :
  constraint-adjusted standard errors could not be calculated because the sampling covariance matrix was uninvertible
> 
> logLik(m1r)
'log Lik.' 822.2163 (df=456)
Warning message:
In warnModelCreatedByOldVersion(model) :
  You are using OpenMx version 2.18.1.29 with a model created by OpenMx version 2.17.3.162. This may work fine (fingers crossed), but if you run into trouble then please recreate your model with the current version of OpenMx.
> 
> logLik(m2r)
'log Lik.' 903.6247 (df=468)
Warning message:
In warnModelCreatedByOldVersion(model) :
  You are using OpenMx version 2.18.1.29 with a model created by OpenMx version 2.17.3.162. This may work fine (fingers crossed), but if you run into trouble then please recreate your model with the current version of OpenMx.
> 
> 
```

**Closed by mhunter1** 2020-09-21 19:43 UTC
